# Generated by Django 5.2.8 on 2025-11-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the job position', max_length=200)),
                ('detailed_description', models.TextField(help_text='Description of the job with markdown content')),
                ('required_skills', models.JSONField(default=list, help_text='Structured list of required skills/qualities for the position')),
                ('is_active', models.BooleanField(default=False, help_text='Boolean flag indicating if this is the active listing')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job Listing',
                'verbose_name_plural': 'Job Listings',
            },
        ),
    ]
