# Generated by Django 5.2.8 on 2025-11-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(help_text='Name of the applicant extracted from the resume filename', max_length=255)),
                ('resume_file', models.FileField(help_text='Reference to the uploaded resume file (PDF/DOCX)', upload_to='resumes/')),
                ('content_hash', models.CharField(help_text='SHA256 hash of the file content for duplicate detection', max_length=64, unique=True)),
                ('file_size', models.PositiveIntegerField(help_text='Size of the uploaded file in bytes')),
                ('file_format', models.CharField(help_text='File format (PDF, DOCX)', max_length=10)),
                ('upload_date', models.DateTimeField(auto_now_add=True, help_text='Timestamp of when the resume was uploaded')),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error')], default='pending', help_text='Current status of AI processing', max_length=20)),
                ('ai_analysis_result', models.JSONField(blank=True, help_text='JSON data containing the results of AI analysis', null=True)),
            ],
            options={
                'verbose_name': 'Applicant',
                'verbose_name_plural': 'Applicants',
                'indexes': [models.Index(fields=['content_hash'], name='jobs_applic_content_4b0c0b_idx'), models.Index(fields=['upload_date'], name='jobs_applic_upload__ed4bb7_idx'), models.Index(fields=['processing_status'], name='jobs_applic_process_125703_idx'), models.Index(fields=['applicant_name'], name='jobs_applic_applica_e892bc_idx')],
            },
        ),
    ]
