# Generated by Django 5.2.8 on 2025-11-10 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='job_listing',
            field=models.ForeignKey(blank=True, help_text='The job listing this applicant has applied for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='jobs.joblisting'),
        ),
    ]
