# Generated by Django 5.2.8 on 2025-11-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_applicant_job_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='analysis_date',
            field=models.DateTimeField(blank=True, help_text='Date when the analysis was completed', null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='categorization',
            field=models.CharField(blank=True, help_text='Categorization (e.g., Senior, Mid-Level, Junior, Mismatched)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='justification_summary',
            field=models.TextField(blank=True, help_text='AI-generated justification for the scores', null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='overall_score',
            field=models.IntegerField(blank=True, help_text='Overall score (0-100) representing fitness for the job', null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='quality_grade',
            field=models.CharField(blank=True, help_text='Quality grade (A, B, C, D, F) reflecting quality of experience', max_length=1, null=True),
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['overall_score'], name='jobs_applic_overall_22547c_idx'),
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['job_listing', 'processing_status'], name='jobs_applic_job_lis_d118c7_idx'),
        ),
    ]
