# Generated by Django 5.2.8 on 2025-11-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_applicant_analysis_date_applicant_categorization_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='analysis_date',
        ),
        migrations.AddField(
            model_name='applicant',
            name='analysis_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('analyzed', 'Analyzed'), ('error', 'Error')], default='pending', help_text='Status of the analysis process', max_length=15),
        ),
        migrations.AddField(
            model_name='applicant',
            name='analysis_timestamp',
            field=models.DateTimeField(blank=True, help_text='Date and time when the analysis was completed', null=True),
        ),
    ]
