# Generated by Django 5.2.8 on 2025-11-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_remove_applicant_analysis_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='parsed_resume_text',
            field=models.TextField(blank=True, help_text='Parsed text content from resume file', null=True),
        ),
    ]
