# Generated by Django 5.2.8 on 2025-11-18 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_applicant_parsed_resume_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='is_shortlisted',
            field=models.BooleanField(default=False, help_text='Flag indicating if the candidate is marked for interview'),
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['is_shortlisted'], name='jobs_applic_is_shor_dc4032_idx'),
        ),
    ]
