# Generated by Django 5.2.8 on 2025-11-19 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_applicant_is_shortlisted_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='applicant',
            name='jobs_applic_is_shor_dc4032_idx',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='is_shortlisted',
        ),
    ]
